language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install --upgrade pip
- pip install .[dev]
before_script:
- flake8 ambix
- flake8 --exclude=tests/data tests
script: py.test tests
deploy:
  provider: pypi
  user: dusktreader
  password:
    secure: cA1E2AwMXUh5l0qSsJmlncK+nMRlkRHoI3vDlmqSUQ7OrnJdPw4JozYUFBuY8xridPOFE2fRtmh63uFD88gYcFFLRuXncYwziMr36QRR94AI/8nl0BdGjzhxMoxnxz3rksI8dLN7LHpyaaS7hn5kPLqx5LLWFDauhzeOTxM4RqQJUcCAr73hAHsB1imIhrfuWmSiaTA4orxokoCb9eE+onYB83P3QN2/JVXfkjlYth1zJUP3h/ZhCkrzhFO2VeuVw8+xxwSTJggLFx43GXXk8llHTOq1A4rbfXISh9aldUV2oBZASgr9FN3tBz3Fgjypv+xUKC8Uxoo4faGJ+viknwBYwc5SuOZsBcOnnXkq6a4Sj+ZlUlNH362VBIA/RElJFYKQFgiEade1QFgtwSOjJhC4pj0kyfxzIh6NDLsbjS1SJkMyOtuIszXB48MfhXJKaW+pdRfCJHGRlZ3H2UQ6wczQw4jDI3OCJ8LNT127zuGfgjsgiRjY0BWL2xwji//E5Qiihu74jw95bu0dy2yz6AKH5ZQi0UQtK8OPXpT4OYlRIt3mQFMsOzMklzkSeA0zFzHATvlBNI5xnpxNexsdzuTDT3LKBZk7DeKUSEoKoVR0E/+vimNFvVCiSGcICf0HxcGFObZAVq1XKWl7SPD0zlf/q9TxymfX5ED/dfLQUEI=
  true:
    tags: true
    distributions: sdist bdist_wheel
    repo: dusktreader/ambix
    python: 3.6
